'use client';

import { useState } from 'react';
import Image from 'next/image';
import { cn } from '@/lib/utils';
import type { CategoryId } from '@/config/categories';

interface SampleImage {
  src: string;
  alt: string;
  style: string;
}

// Placeholder samples per category — replace with real generated examples
const CATEGORY_SAMPLES: Partial<Record<CategoryId, SampleImage[]>> = {
  headshots: [
    { src: '/samples/headshots/1.jpg', alt: 'Professional headshot — corporate style', style: 'Corporate' },
    { src: '/samples/headshots/2.jpg', alt: 'Professional headshot — creative style', style: 'Creative' },
    { src: '/samples/headshots/3.jpg', alt: 'Professional headshot — modern style', style: 'Modern' },
    { src: '/samples/headshots/4.jpg', alt: 'Professional headshot — executive style', style: 'Executive' },
  ],
  dating: [
    { src: '/samples/dating/1.jpg', alt: 'Dating profile photo — outdoor style', style: 'Outdoor' },
    { src: '/samples/dating/2.jpg', alt: 'Dating profile photo — casual style', style: 'Casual' },
    { src: '/samples/dating/3.jpg', alt: 'Dating profile photo — lifestyle style', style: 'Lifestyle' },
    { src: '/samples/dating/4.jpg', alt: 'Dating profile photo — urban style', style: 'Urban' },
  ],
  'pet-portraits': [
    { src: '/samples/pet-portraits/1.jpg', alt: 'Pet portrait — royal style', style: 'Royal' },
    { src: '/samples/pet-portraits/2.jpg', alt: 'Pet portrait — watercolor style', style: 'Watercolor' },
    { src: '/samples/pet-portraits/3.jpg', alt: 'Pet portrait — pop art style', style: 'Pop Art' },
    { src: '/samples/pet-portraits/4.jpg', alt: 'Pet portrait — renaissance style', style: 'Renaissance' },
  ],
};

// Generic samples for categories that don't have specific ones yet
const GENERIC_SAMPLES: SampleImage[] = [
  { src: '/samples/generic/1.jpg', alt: 'AI-generated photo example', style: 'Style 1' },
  { src: '/samples/generic/2.jpg', alt: 'AI-generated photo example', style: 'Style 2' },
  { src: '/samples/generic/3.jpg', alt: 'AI-generated photo example', style: 'Style 3' },
  { src: '/samples/generic/4.jpg', alt: 'AI-generated photo example', style: 'Style 4' },
];

interface SampleGalleryProps {
  categoryId: CategoryId;
  categoryName: string;
  outputLabel: string;
}

export function SampleGallery({ categoryId, categoryName, outputLabel }: SampleGalleryProps) {
  const samples = CATEGORY_SAMPLES[categoryId] || GENERIC_SAMPLES;
  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <section className="py-20">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <h2 className="text-center font-display text-3xl font-normal text-tp-ink">
          Example {categoryName}
        </h2>
        <p className="mx-auto mt-4 max-w-2xl text-center text-tp-muted">
          See what our AI can create. These are examples of {outputLabel} generated by our platform.
        </p>

        {/* Gallery grid */}
        <div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-4 sm:gap-6">
          {samples.map((sample, i) => (
            <button
              key={i}
              onClick={() => setActiveIndex(i)}
              className={cn(
                'group relative aspect-[3/4] overflow-hidden rounded-tp-card border-2 transition-all',
                activeIndex === i
                  ? 'border-tp-bronze ring-2 ring-tp-beige/40 shadow-lg scale-[1.02]'
                  : 'border-tp-line hover:border-tp-bronze/50 hover:shadow-md'
              )}
            >
              {/* Placeholder — shows a styled gradient when no real image exists */}
              <div className="absolute inset-0 bg-gradient-to-br from-tp-paper via-tp-beige/40 to-tp-bronze/20 flex items-center justify-center">
                <div className="text-center">
                  <div className="text-4xl opacity-40">📸</div>
                  <p className="mt-2 text-xs text-tp-muted/60 font-medium">{sample.style}</p>
                </div>
              </div>
              {/* Style label */}
              <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/60 to-transparent p-3">
                <span className="text-xs font-medium text-white">{sample.style}</span>
              </div>
            </button>
          ))}
        </div>

        <p className="mt-8 text-center text-xs text-tp-muted/60">
          These are AI-generated concept examples. Actual results vary based on your photos.
        </p>
      </div>
    </section>
  );
}
