'use client';

import { useState } from 'react';
import { cn } from '@/lib/utils';
import { Camera, User, Heart, PawPrint, Briefcase, Palette } from 'lucide-react';
import type { CategoryId } from '@/config/categories';

interface SampleStyle {
  label: string;
  gradient: string;
  pattern: 'lines' | 'dots' | 'circles' | 'grid';
}

const CATEGORY_STYLES: Partial<Record<CategoryId, SampleStyle[]>> = {
  headshots: [
    { label: 'Corporate', gradient: 'from-tp-beige/60 via-tp-paper to-tp-bronze/30', pattern: 'lines' },
    { label: 'Creative', gradient: 'from-tp-bronze/20 via-tp-beige/30 to-tp-paper', pattern: 'dots' },
    { label: 'Modern', gradient: 'from-tp-paper via-tp-beige/50 to-tp-bronze/20', pattern: 'circles' },
    { label: 'Executive', gradient: 'from-tp-bronze/30 via-tp-paper to-tp-beige/40', pattern: 'grid' },
  ],
  dating: [
    { label: 'Outdoor', gradient: 'from-emerald-50 via-tp-paper to-tp-beige/30', pattern: 'dots' },
    { label: 'Casual', gradient: 'from-tp-beige/40 via-tp-paper to-sky-50', pattern: 'circles' },
    { label: 'Lifestyle', gradient: 'from-amber-50 via-tp-paper to-tp-beige/30', pattern: 'lines' },
    { label: 'Urban', gradient: 'from-slate-100 via-tp-paper to-tp-beige/20', pattern: 'grid' },
  ],
  'pet-portraits': [
    { label: 'Royal', gradient: 'from-tp-bronze/30 via-tp-paper to-purple-50', pattern: 'lines' },
    { label: 'Watercolor', gradient: 'from-sky-50 via-tp-paper to-rose-50', pattern: 'dots' },
    { label: 'Pop Art', gradient: 'from-amber-50 via-tp-paper to-pink-50', pattern: 'circles' },
    { label: 'Renaissance', gradient: 'from-tp-beige/50 via-tp-paper to-tp-bronze/20', pattern: 'grid' },
  ],
};

const GENERIC_STYLES: SampleStyle[] = [
  { label: 'Style A', gradient: 'from-tp-paper via-tp-beige/40 to-tp-bronze/20', pattern: 'lines' },
  { label: 'Style B', gradient: 'from-tp-bronze/20 via-tp-paper to-tp-beige/30', pattern: 'dots' },
  { label: 'Style C', gradient: 'from-tp-beige/40 via-tp-paper to-tp-bronze/15', pattern: 'circles' },
  { label: 'Style D', gradient: 'from-tp-paper via-tp-bronze/15 to-tp-beige/30', pattern: 'grid' },
];

const CATEGORY_ICONS: Partial<Record<CategoryId, typeof Camera>> = {
  headshots: Briefcase,
  dating: Heart,
  'pet-portraits': PawPrint,
};

function PatternSVG({ pattern, className }: { pattern: string; className?: string }) {
  return (
    <svg className={cn('absolute inset-0 h-full w-full opacity-[0.08]', className)} xmlns="http://www.w3.org/2000/svg">
      {pattern === 'lines' && (
        <pattern id="p-lines" width="20" height="20" patternUnits="userSpaceOnUse">
          <path d="M0 10h20" stroke="#76563D" strokeWidth="0.5" fill="none" />
        </pattern>
      )}
      {pattern === 'dots' && (
        <pattern id="p-dots" width="16" height="16" patternUnits="userSpaceOnUse">
          <circle cx="8" cy="8" r="1.5" fill="#76563D" />
        </pattern>
      )}
      {pattern === 'circles' && (
        <pattern id="p-circles" width="32" height="32" patternUnits="userSpaceOnUse">
          <circle cx="16" cy="16" r="8" stroke="#76563D" strokeWidth="0.5" fill="none" />
        </pattern>
      )}
      {pattern === 'grid' && (
        <pattern id="p-grid" width="24" height="24" patternUnits="userSpaceOnUse">
          <path d="M24 0v24M0 24h24" stroke="#76563D" strokeWidth="0.3" fill="none" />
        </pattern>
      )}
      <rect width="100%" height="100%" fill={`url(#p-${pattern})`} />
    </svg>
  );
}

interface SampleGalleryProps {
  categoryId: CategoryId;
  categoryName: string;
  outputLabel: string;
}

export function SampleGallery({ categoryId, categoryName, outputLabel }: SampleGalleryProps) {
  const styles = CATEGORY_STYLES[categoryId] || GENERIC_STYLES;
  const [activeIndex, setActiveIndex] = useState(0);
  const IconComponent = CATEGORY_ICONS[categoryId] || User;

  return (
    <section className="py-20">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <h2 className="text-center font-display text-3xl font-normal text-tp-ink">
          Example {categoryName}
        </h2>
        <p className="mx-auto mt-4 max-w-2xl text-center text-tp-muted">
          See what our AI can create. These are examples of {outputLabel} generated by our platform.
        </p>

        {/* Gallery grid */}
        <div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-4 sm:gap-6">
          {styles.map((style, i) => (
            <button
              key={style.label}
              onClick={() => setActiveIndex(i)}
              className={cn(
                'group relative aspect-[3/4] overflow-hidden rounded-tp-card border-2 transition-all duration-200',
                activeIndex === i
                  ? 'border-tp-bronze ring-2 ring-tp-beige/40 shadow-lg scale-[1.02]'
                  : 'border-tp-line hover:border-tp-bronze/50 hover:shadow-md'
              )}
            >
              {/* Generative background */}
              <div className={cn('absolute inset-0 bg-gradient-to-br', style.gradient)} />
              <PatternSVG pattern={style.pattern} />

              {/* Centered icon */}
              <div className="absolute inset-0 flex flex-col items-center justify-center gap-3">
                <span className={cn(
                  'flex h-14 w-14 items-center justify-center rounded-full transition-all duration-200',
                  activeIndex === i
                    ? 'bg-tp-black text-tp-bronze shadow-lg'
                    : 'bg-tp-beige/50 text-tp-bronze-ink group-hover:bg-tp-black group-hover:text-tp-bronze'
                )}>
                  <IconComponent className="h-6 w-6" aria-hidden="true" />
                </span>
                <Palette className={cn(
                  'h-3.5 w-3.5 transition-opacity duration-200',
                  activeIndex === i ? 'text-tp-bronze-ink opacity-100' : 'text-tp-muted opacity-0 group-hover:opacity-60'
                )} aria-hidden="true" />
              </div>

              {/* Style label */}
              <div className={cn(
                'absolute bottom-0 inset-x-0 p-3 text-center transition-all duration-200',
                activeIndex === i
                  ? 'bg-tp-black/80'
                  : 'bg-tp-black/50 group-hover:bg-tp-black/70'
              )}>
                <span className="text-xs font-semibold tracking-wide text-white">{style.label}</span>
              </div>
            </button>
          ))}
        </div>

        <p className="mt-8 text-center text-xs text-tp-muted">
          These are AI-generated concept examples. Actual results vary based on your photos.
        </p>
      </div>
    </section>
  );
}
