export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  country: string;
  heroTitle: string;
  heroDescription: string;
  localContext: string;
  industries: string[];
  nearbyAreas: string[];
}

export const CITIES: CityData[] = [
  {
    slug: 'new-york',
    name: 'New York City',
    state: 'New York',
    stateAbbr: 'NY',
    country: 'US',
    heroTitle: 'AI Headshots in New York City',
    heroDescription: 'Skip the NYC studio fees. Get professional AI headshots from your phone — perfect for Wall Street, Midtown offices, and everything in between.',
    localContext: 'In a city where first impressions close deals, your headshot needs to match the pace. Whether you work in finance on Wall Street, tech in Flatiron, or media in Midtown, a polished profile photo opens doors.',
    industries: ['Finance', 'Media', 'Tech', 'Law', 'Fashion', 'Real Estate'],
    nearbyAreas: ['Brooklyn', 'Jersey City', 'Hoboken', 'Long Island', 'Westchester'],
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'California',
    stateAbbr: 'CA',
    country: 'US',
    heroTitle: 'AI Headshots in Los Angeles',
    heroDescription: 'Professional headshots without the LA studio prices. Upload selfies, get studio-quality results for auditions, LinkedIn, and everything else.',
    localContext: 'From entertainment in Hollywood to tech on the Westside, LA professionals need headshots that stand out. Whether you are an actor, entrepreneur, or creative, quality photos are non-negotiable here.',
    industries: ['Entertainment', 'Tech', 'Creative', 'Real Estate', 'Healthcare', 'Legal'],
    nearbyAreas: ['Santa Monica', 'Pasadena', 'Burbank', 'Long Beach', 'Orange County'],
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'Illinois',
    stateAbbr: 'IL',
    country: 'US',
    heroTitle: 'AI Headshots in Chicago',
    heroDescription: 'Professional headshots for Chicago professionals. No studio needed — upload selfies and get polished results for the Loop, Magnificent Mile, and beyond.',
    localContext: 'Chicago is a city of industries — from trading floors in the Loop to tech corridors in River North. Your headshot should reflect the same professionalism you bring to the table every day.',
    industries: ['Finance', 'Manufacturing', 'Tech', 'Consulting', 'Healthcare', 'Legal'],
    nearbyAreas: ['Evanston', 'Oak Park', 'Naperville', 'Schaumburg', 'Waukegan'],
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    state: 'California',
    stateAbbr: 'CA',
    country: 'US',
    heroTitle: 'AI Headshots in San Francisco',
    heroDescription: 'Tech-forward headshots for the Bay Area. Upload selfies, skip the studio, and get AI-generated professional photos in hours.',
    localContext: 'In the tech capital of the world, your online presence is your resume. From SoMa startups to Financial District firms, a sharp headshot signals you belong.',
    industries: ['Tech', 'Venture Capital', 'Biotech', 'Finance', 'Design', 'Legal'],
    nearbyAreas: ['Oakland', 'San Jose', 'Palo Alto', 'Berkeley', 'Mountain View'],
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'Texas',
    stateAbbr: 'TX',
    country: 'US',
    heroTitle: 'AI Headshots in Houston',
    heroDescription: 'Professional AI headshots for Houston professionals. Perfect for energy, healthcare, and corporate roles — no studio appointment needed.',
    localContext: 'Houston powers industries from energy to medicine. Whether you work in the Energy Corridor, the Texas Medical Center, or downtown, a professional headshot builds trust with clients and colleagues.',
    industries: ['Energy', 'Healthcare', 'Engineering', 'Legal', 'Real Estate', 'Finance'],
    nearbyAreas: ['The Woodlands', 'Sugar Land', 'Katy', 'Pearland', 'Galveston'],
  },
  {
    slug: 'miami',
    name: 'Miami',
    state: 'Florida',
    stateAbbr: 'FL',
    country: 'US',
    heroTitle: 'AI Headshots in Miami',
    heroDescription: 'Professional headshots for Miami professionals. From Brickell to Coral Gables — studio-quality photos without leaving your home.',
    localContext: 'Miami is where business meets style. Whether you are in real estate in Brickell, finance in Coral Gables, or hospitality in South Beach, your headshot sets the tone.',
    industries: ['Real Estate', 'Finance', 'Hospitality', 'Tech', 'Legal', 'Healthcare'],
    nearbyAreas: ['Fort Lauderdale', 'Coral Gables', 'Boca Raton', 'West Palm Beach', 'Aventura'],
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    state: 'Texas',
    stateAbbr: 'TX',
    country: 'US',
    heroTitle: 'AI Headshots in Dallas',
    heroDescription: 'Professional headshots for Dallas–Fort Worth professionals. Upload selfies, get polished results — no studio needed.',
    localContext: 'Dallas means business, from the corporate towers in Uptown to the tech scene in Deep Ellum. A professional headshot is your handshake before the handshake.',
    industries: ['Corporate', 'Tech', 'Finance', 'Real Estate', 'Legal', 'Healthcare'],
    nearbyAreas: ['Fort Worth', 'Plano', 'Arlington', 'Frisco', 'Irving'],
  },
  {
    slug: 'boston',
    name: 'Boston',
    state: 'Massachusetts',
    stateAbbr: 'MA',
    country: 'US',
    heroTitle: 'AI Headshots in Boston',
    heroDescription: 'Professional AI headshots for Boston professionals. From academia to biotech — polished photos delivered in hours.',
    localContext: 'Boston blends centuries of tradition with cutting-edge innovation. From Harvard and MIT to the biotech hub in Kendall Square, your headshot should project the credibility this city demands.',
    industries: ['Biotech', 'Education', 'Healthcare', 'Finance', 'Tech', 'Legal'],
    nearbyAreas: ['Cambridge', 'Brookline', 'Somerville', 'Newton', 'Quincy'],
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    state: 'Washington',
    stateAbbr: 'WA',
    country: 'US',
    heroTitle: 'AI Headshots in Seattle',
    heroDescription: 'AI-powered headshots for Seattle professionals. Perfect for tech, healthcare, and creative roles — no studio session required.',
    localContext: 'Home to some of the biggest names in tech and a growing startup ecosystem, Seattle professionals need headshots that are polished yet approachable. Skip the rain-day studio reschedule.',
    industries: ['Tech', 'Aerospace', 'Healthcare', 'Creative', 'Retail', 'Consulting'],
    nearbyAreas: ['Bellevue', 'Redmond', 'Tacoma', 'Kirkland', 'Everett'],
  },
  {
    slug: 'denver',
    name: 'Denver',
    state: 'Colorado',
    stateAbbr: 'CO',
    country: 'US',
    heroTitle: 'AI Headshots in Denver',
    heroDescription: 'Professional headshots for Denver professionals. From LoDo to the Tech Center — studio-quality photos from your phone.',
    localContext: 'Denver is one of the fastest-growing business hubs in the country. Whether you are in energy, tech, or outdoor industry, a professional headshot helps you stand out in this competitive market.',
    industries: ['Tech', 'Energy', 'Aerospace', 'Healthcare', 'Real Estate', 'Outdoor Industry'],
    nearbyAreas: ['Boulder', 'Aurora', 'Lakewood', 'Colorado Springs', 'Fort Collins'],
  },
  {
    slug: 'austin',
    name: 'Austin',
    state: 'Texas',
    stateAbbr: 'TX',
    country: 'US',
    heroTitle: 'AI Headshots in Austin',
    heroDescription: 'Professional AI headshots for Austin professionals. From tech to music — polished photos without the studio hassle.',
    localContext: 'Austin has become a tech powerhouse while keeping its creative spirit. Whether you are a startup founder on South Congress, a developer in the Domain, or a creative in East Austin, your headshot should match your ambition.',
    industries: ['Tech', 'Creative', 'Music', 'Real Estate', 'Healthcare', 'Education'],
    nearbyAreas: ['Round Rock', 'Cedar Park', 'Georgetown', 'San Marcos', 'Pflugerville'],
  },
  {
    slug: 'atlanta',
    name: 'Atlanta',
    state: 'Georgia',
    stateAbbr: 'GA',
    country: 'US',
    heroTitle: 'AI Headshots in Atlanta',
    heroDescription: 'Professional headshots for Atlanta professionals. From Buckhead to Midtown — skip the studio, get results in hours.',
    localContext: 'Atlanta is the business capital of the Southeast. From Fortune 500 headquarters in Buckhead to the tech scene in Midtown, a professional headshot is essential for making the right impression.',
    industries: ['Corporate', 'Tech', 'Media', 'Healthcare', 'Finance', 'Real Estate'],
    nearbyAreas: ['Marietta', 'Decatur', 'Sandy Springs', 'Alpharetta', 'Roswell'],
  },
  {
    slug: 'washington-dc',
    name: 'Washington, D.C.',
    state: 'District of Columbia',
    stateAbbr: 'DC',
    country: 'US',
    heroTitle: 'AI Headshots in Washington, D.C.',
    heroDescription: 'Professional headshots for D.C. professionals. From Capitol Hill to K Street — polished photos without the scheduling hassle.',
    localContext: 'In the nation\'s capital, your professional image carries weight. Whether you work in government, consulting, nonprofits, or lobbying, a sharp headshot is part of the job.',
    industries: ['Government', 'Consulting', 'Nonprofit', 'Legal', 'Defense', 'Policy'],
    nearbyAreas: ['Arlington', 'Bethesda', 'Alexandria', 'Silver Spring', 'Tysons'],
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'Arizona',
    stateAbbr: 'AZ',
    country: 'US',
    heroTitle: 'AI Headshots in Phoenix',
    heroDescription: 'Professional AI headshots for Phoenix professionals. Get studio-quality results without braving the heat for a photo session.',
    localContext: 'Phoenix is one of the fastest-growing metros in the US. With booming tech, real estate, and healthcare sectors, professionals here need headshots that match the city\'s growth.',
    industries: ['Tech', 'Real Estate', 'Healthcare', 'Finance', 'Manufacturing', 'Education'],
    nearbyAreas: ['Scottsdale', 'Tempe', 'Mesa', 'Chandler', 'Gilbert'],
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    country: 'US',
    heroTitle: 'AI Headshots in Philadelphia',
    heroDescription: 'Professional headshots for Philadelphia professionals. From Center City to University City — polished photos from your phone.',
    localContext: 'Philadelphia blends historic institutions with modern innovation. From healthcare giants to the growing tech scene, professionals here need headshots that project both tradition and forward thinking.',
    industries: ['Healthcare', 'Education', 'Finance', 'Tech', 'Legal', 'Pharma'],
    nearbyAreas: ['Cherry Hill', 'King of Prussia', 'Wilmington', 'Camden', 'Conshohocken'],
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    country: 'US',
    heroTitle: 'AI Headshots in Nashville',
    heroDescription: 'Professional AI headshots for Nashville professionals. From Music Row to the Gulch — studio-quality photos in hours.',
    localContext: 'Nashville is more than music — it is a rapidly growing hub for healthcare, tech, and corporate headquarters. Your headshot should reflect the city\'s mix of creativity and business acumen.',
    industries: ['Healthcare', 'Music', 'Tech', 'Corporate', 'Hospitality', 'Real Estate'],
    nearbyAreas: ['Franklin', 'Murfreesboro', 'Brentwood', 'Hendersonville', 'Gallatin'],
  },
  {
    slug: 'portland',
    name: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    country: 'US',
    heroTitle: 'AI Headshots in Portland',
    heroDescription: 'Professional headshots for Portland professionals. From the Pearl District to the tech corridor — skip the studio.',
    localContext: 'Portland marries creativity with technology. Whether you are in the outdoor industry, tech, or creative services, your headshot should be as authentic and polished as the work you do.',
    industries: ['Tech', 'Creative', 'Outdoor Industry', 'Healthcare', 'Manufacturing', 'Design'],
    nearbyAreas: ['Beaverton', 'Lake Oswego', 'Hillsboro', 'Vancouver WA', 'Tigard'],
  },
  {
    slug: 'minneapolis',
    name: 'Minneapolis',
    state: 'Minnesota',
    stateAbbr: 'MN',
    country: 'US',
    heroTitle: 'AI Headshots in Minneapolis',
    heroDescription: 'Professional AI headshots for Minneapolis–Saint Paul professionals. No need to brave the cold for a studio session.',
    localContext: 'The Twin Cities are home to major corporations and a thriving startup scene. From the IDS Center to the North Loop, professionals here value both substance and presentation.',
    industries: ['Corporate', 'Healthcare', 'Finance', 'Tech', 'Retail', 'Manufacturing'],
    nearbyAreas: ['Saint Paul', 'Bloomington', 'Eden Prairie', 'Plymouth', 'Edina'],
  },
  {
    slug: 'san-diego',
    name: 'San Diego',
    state: 'California',
    stateAbbr: 'CA',
    country: 'US',
    heroTitle: 'AI Headshots in San Diego',
    heroDescription: 'Professional headshots for San Diego professionals. From biotech to defense — polished AI photos without the studio trip.',
    localContext: 'San Diego is a hub for biotech, defense, and tourism. Whether you work in Sorrento Valley, Downtown, or on base, a professional headshot helps you make the right first impression.',
    industries: ['Biotech', 'Defense', 'Tech', 'Healthcare', 'Tourism', 'Real Estate'],
    nearbyAreas: ['La Jolla', 'Carlsbad', 'Chula Vista', 'Encinitas', 'Oceanside'],
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    state: 'North Carolina',
    stateAbbr: 'NC',
    country: 'US',
    heroTitle: 'AI Headshots in Charlotte',
    heroDescription: 'Professional AI headshots for Charlotte professionals. The banking capital deserves polished photos — no studio needed.',
    localContext: 'As the second-largest banking center in the US, Charlotte professionals understand the importance of presentation. From Uptown towers to South End startups, your headshot is your brand.',
    industries: ['Banking', 'Finance', 'Tech', 'Energy', 'Healthcare', 'Real Estate'],
    nearbyAreas: ['Concord', 'Huntersville', 'Matthews', 'Gastonia', 'Rock Hill'],
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
