export const PACKAGES = {
  express: {
    id: 'express',
    name: 'Express',
    price: 1990,
    currency: 'usd',
    headshots: 10,
    backgrounds: 2,
    styles: 2,
    resolution: 'hd',
    features: [],
  },
  starter: {
    id: 'starter',
    name: 'Starter',
    price: 2990,
    currency: 'usd',
    headshots: 40,
    backgrounds: 5,
    styles: 3,
    resolution: 'hd',
    features: [],
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    price: 4990,
    currency: 'usd',
    headshots: 80,
    backgrounds: 10,
    styles: 6,
    resolution: 'hd',
    features: ['linkedin_banner'],
    recommended: true,
  },
  executive: {
    id: 'executive',
    name: 'Executive',
    price: 8990,
    currency: 'usd',
    headshots: 160,
    backgrounds: 15,
    styles: 10,
    resolution: '4k',
    features: ['linkedin_banner', 'email_signature', 'priority_support'],
  },
} as const;

export type PackageId = keyof typeof PACKAGES;
export type Package = (typeof PACKAGES)[PackageId];
